sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.2.3
  - 2.3.0
  - jruby-1.7.23
services:
  - rabbitmq
  - redis
notifications:
  irc:
    - "irc.freenode.net#sensu"
script: "bundle exec rspec . --tag ~ssl"
addons:
  code_climate:
    repo_token: 629d024a848e2ebb1b0c0283c2046387c1b8c0d1cfd4d03289bef74a7b875d55
